[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'

[[plugins]] # colorschema TODO it too old so should been replaced
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]] # slimのハイライト
repo = 'slim-template/vim-slim'

[[plugins]] # インデントを見やすく
repo = 'Yggdroot/indentLine'

[[plugins]] # j,kによる移動を爆速に
repo = 'rhysd/accelerated-jk'
